http://localhost:3002

Content-Type: application/json

POST /register
{
  "email": "test@test.com",
  "password": "12345678"
}

http://localhost:3002

Content-Type: application/json

POST /login
{
  "email": "test@test.com",
  "password": "12345678"
}

http://localhost:3002

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpYXQiOjE2MjcyNDk0NTYsImV4cCI6MTYyNzI0OTUwMX0.TtWRHFxELxA6SByESMlgn6NHUbPUBBZd3Xu2P4N7KjQ

GET /

http://localhost:3002

Content-Type: application/json

POST /refresh
{
  "email": "test@test.com",
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpYXQiOjE2MjcyNTkzMzR9.8TtpFNkiK54Mcfd_pg2QK0Hx_9WXeD1eyn3SM_Ba0Dw"
}

# {
#     "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpYXQiOjE2MjcyNTkzMzQsImV4cCI6MTYyNzI1OTM3OX0.lufoRp0lweC5kIZ2R3sqHJbB4bFRFE4CEeYs8MM3sHQ",
#     "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpYXQiOjE2MjcyNTkzMzR9.8TtpFNkiK54Mcfd_pg2QK0Hx_9WXeD1eyn3SM_Ba0Dw",
#     "success": true
# }
